title: "Esoteric Arts"
email: esotericartsemail@proton.me
description: "Exploring mythology, comics, and storytelling through our authors and works."
baseurl: "" 
url: "https://solomonthazar-star.github.io/Esoteric-Arts"

# Theme (professional look)
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Navigation bar
header_pages:
  - index.md
  - about.md
  - authors.md
  - works.md
  - contact.md

# Custom includes
include:
  - _includes/head-custom.html
